os:
- linux
language: node_js
node_js:
- '6'
script:
- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
- git fetch origin
- git checkout $TRAVIS_BRANCH || git checkout -b $TRAVIS_BRANCH
- yarn test
- yarn run reg-suit -- --test
env:
  global:
  - secure: dXakyAfnVHCzA60ApEja+29lPZwCI8wY69H2YiHZcDm9tHAJSoDpDisdDRhF2IkYgRTm6HxHOlBpnnAfvQcU+00RGfd15YVOO4yr2auQomB09vtsKuvvqbaF9buQZ1pXXLTvIs1B/nB1vom0NNyNMUmpwoOS8hmVVemyueMAJDp7a/7rpkQItZfHCIwHtK2fEXNdSXGV9M3k5cF5Bss4nlTLzRVbBvNFfuKE8DxEOKwdDrELS8eFg8Qtn2q5/Lznge72mMOQEETI6BMtPUYNtOPxgaPMKy/hTvG/XxEilIQ9syWvPoAkoAVahOIECXMbM3HsfquCK4F2u4LiTtFUS9KIEO0PuZhY85E27zJIB4u0HXsNvvBBn2q2oZeiOE+XGnFomZnvNh8s1Ls59Z/j1bZpsL24iP4UyuyEOVLhhH+lEBTDnapCG15kERnTPCN9dof3fjEu/1wFRk3Nz+5tPl0CxR54ttkF03jpY1GnKgrCCDLD7QGoi0E0+wzhNIcIvpaIZm6ny7FH/LeCVjYZENlLRNPBuk3PTJXy8efcHd/ec1QmP6ubXonD7n8TgKzsFV0r7YOLoi3maAG5e6KbxBSkRt0H3/dIy1pmLclGCsndVo1gXaTFr8rkwrk1iEgio/62AruRassYl9VWpeNjMGjGSmwBfBmHozyJ97lwlv4=
  - secure: C0hcr/vzA+x4ztC52f4Nacv1F09xUK3aAfpuUsTnc4QpaJkckmqbZLUxhoGkiJ5loMXq6j7ShZ9xiAqfmNofFShDutggsfrxHdbN3AXpuX9p6KIAoz0ucJ8VRp9Gz/ThbuopLDjU6OstuRtJHN8rHTEt+dnuJHf0vrBa3iGz1tiKVHp5r45QdGTnCjGG5wfxzpp0q0jy1sbnQBWQeWviroKMbYsdgSIvu2YCx27KeEncmb8avSK2L6kW7F/5LPo+Wgue5xyVyLCLNJBPwciygZkLAhIaPlSM907ZcOqaV7K213EaETBZLzecu1JXX1l3NOsV4oOFN+whF6XFdfuU5rlfLLLZcxSQ800tn5o8kNHmLGv+O4i8VwCRhhEzuuUW9N9ry81UCzv6RR42VnnWSQ00D/gw1QaowWu/NQa7eQhdbUydhSzrdFxyRjBQKyGFR8wpTLR4t8UxctxXbLaaJOL9mpkVGd12o4bZxMkLOaknZ9GOpaBdeFep2Ne2m6P/cyzVZZbLaLi+ev+epssZF+CCT4CtSAdrj4O3nlw9qvSfUjJiClyzs5jEiuVOVEIqqWyNVXV+8L/2yF+zFfOkE8q/GWutuHcD3Zat5OdPWNpEYlfi1WYW+GVlU93sTGzNi2JQNJ+9pmZ2bzkzTVwa8AM3qFiIV6MVpDJytAFEMhQ=
