os:
- linux
language: node_js
node_js:
- '6'
script:
- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
- git fetch origin
- git checkout $TRAVIS_BRANCH || git checkout -b $TRAVIS_BRANCH
- yarn test
- yarn run reg-suit -- --test
env:
  global:
  - secure: OhvKuG6cUqVAEwhiKZKucp2sK7krPqmRxA9jtEJKv6mpSWNpPzJ0xXxm8Y/ctmsL5vXFFDlVyksgplyTeU2eKqOfQMhYVU91MWNTJFuYU5ugHDFWwfq1OtbypEe2WJWyOZOtPlovqHjRfKOZT6GvuI7/jx0ThmZXvCyfVpKS4V0HjISBVG9QN208HasRzDdsm7DTld9KobKQQmNe80d1cNVgqslua2nplTTV7VrgCtygVAkIROVUmUddwTrpxFjK18BTsYs1VMxd4GlOKXZ/S2LmBbmhSYS8sAUhPkSQn+YYyNtzmnZS6ueXHbD4AQfUSTzNvoxe7st6ZToYUvlUtvgKVBsIpi/GikHL6oa7VUWafPwf9mrRxmJ4b7Fu5YWli6TwDyQIoxpszJSWEyM+2lnyktfA6Xnx5bDPHSeTlGrj6iB591owASZTykc3SW4LUq72Bdt4tvuMs0GVBVREymF1GBPFZ2D6xFeI8jJd6ngXCLq7VIjQ1I3fhyGQCWLeYL7k2Fi/swsfH/9CQ0KUYGgFDo2yxKqLd+uU/wnP3pUMSRI1pvjHaPoQJYU/aHvWKmMm4iYuwnc7UWCNLHG9RV0jhyn2xvZ2qVn3KeALew6qKZmvgWfuJK+VD5zSPDiL251qwNQ/mClLOF8UJPN1zxss90vU4vOAdr/vFRvm/RY=
  - secure: evqsIY9WG1wsZFRIwq/GHug+t7HU+MEPvgQ4TxObSa9T/3w8aUmtBHEd0DHyA+gOKnAfXAQFqZGJCGARZc7DS/zSB0Wjl2ATx5m7Szii/ncdmAFTY+krpOadZDENUsk9dXyj0jTm7Vy+zNIP83qGzExAzM7z93vKX1jDnyFPLn4xtuKfjGEYjDXX2sUwyd75Xt/UT7iRZD32SwXbT7qUKbVtfc9ryelYb1MsKUFG8H+ry3pxuQ8iWc5hIUoK6HvLB6ysinVKN5SZ0LRC72iOWn7FLQvwdfSFkt4tGM2uifvPOxaJXCddrF47UHfN4BytDHTHOAsBc0qlA5wIezwhRuKK4Oq0o0g+wGLoJeDsZUYioWYIB8JcI6b7FewtRIpCIJJyHEgSHWIOXQCouzz8Zjwyj//8wyhXOMzJM6TQ4rMX6lykXMLjXey3BXFklO3p+R0RXexkz1wXc6U1HbKkRpCcM0qy4eRFn99OC94lC9SagFrusAbCukJCFrHVpwO2tBvDCNSOCOZsTBGYpQafBN/c+ZlhhiZlBrr5nt/8HXfCNmdllr9dGaYhug/FuGoLWkI9Q5aht+WAtPBgjrLSl+ny5DaC21l+jPYU6ga4NjMPOOS1x/SL4x/cyIE0kTOBUMtVuwa6mlZB3lztKaBa3l3dKH8oZoizArdFkY1SEJc=
